# Generated by Django 5.2.14 on 2026-05-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='is_vendor',
            field=models.BooleanField(default=False),
        ),
    ]
