# Generated by Django 5.2.14 on 2026-05-24 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_vendor',
        ),
    ]
