# Generated by Django 5.2.14 on 2026-05-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_profile_is_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ManyToManyField(related_name='product_image', to='app1.image'),
        ),
    ]
